name: "Unit: Python Versions"
on:
  pull_request:
  push:
concurrency:
  group: 'ci-${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
defaults:
  run:
    shell: sh -ex {0}
jobs:
  unittests:
    strategy:
      matrix:
        python-version: ["3.13"]
        toxenv: [py3]
        slug: [""]
        experimental: [false]
        check-latest: [false]
        continue-on-error: [false]
    name: Python ${{matrix.python-version}} ${{ matrix.slug }}
    runs-on: macos-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Install Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          check-latest: ${{matrix.check-latest}}
      - name: Install tox
        run: pip install tox
      - name: Run unittest
        env: 
          TMPDIR: '/tmp/'
        run: tox -e ${{ matrix.toxenv }} -- --color=yes
